
services:

  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    container_name: gateway
    depends_on:
      - auth
      - projets
      - users
      - groupes
      #- grades
      - reports
      - promotions
      - notations
      - livrables
      # - soutenances
    networks:
      - backend

    environment:
      - DOCKER=true
    env_file:
      - ./api-gateway/.env

  auth:
    build: ./auth-service
    ports:
      - "3001:3001"
    container_name: auth
    env_file:
      - ./auth-service/.env
    networks:
      - backend
   


  projets:
    build: ./project-service
    ports:
      - "3002:3002"
    container_name: projets
    env_file:
      - ./project-service/.env
    networks:
      - backend


  users:
    build: ./user-service
    ports:
      - "3003:3003"
    container_name: users
    env_file:
      - ./user-service/.env
    networks:
       - backend

  groupes:
    build: ./group-service
    ports:
      - "3004:3004"
    container_name: groupes
    env_file:
      - ./group-service/.env
    networks:
      - backend

  #grades:
  #  build: ./grade-service
  #  ports:
  #    - "3005:3005"
  #  container_name: grades
  #  env_file:
  #    - ./grade-service/.env
  #  networks:
  #    - backend

  reports:
    build: ./report-service
    ports:
      - "3006:3006"
    container_name: reports
    env_file:
      - ./report-service/.env
    networks:
      - backend

  promotions:
    build: ./promotion-service
    ports:
      - "3007:3007"
    container_name: promotions
    env_file:
      - ./promotion-service/.env
    networks:
      - backend

  notations:
    build: ./notation-service
    ports:
      - "3005:3005"
    container_name: notations
    env_file:
      - ./notation-service/.env
    networks:
      - backend

  livrables:
    build: ./livrable-service
    ports:
      - "3009:3009"
    container_name: deliverables
    env_file:
      - ./livrable-service/.env
    networks:
      - backend

  soutenances:
    build: ./soutenance-service
    ports:
      - "3010:3010"
    env_file:
      - ./soutenance-service/.env
    container_name: soutenances
    networks:
      - backend

  # notifications:
  #   build: ./notification-service
  #   ports:
  #     - "3011:3011"
  #   container_name: notifications
  #   networks:
  #     - backend

volumes:
  mysql_data:

networks:
  backend:
    # driver: bridge