
services:
  projects:
    build: .
    container_name: service-projects
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    #external: true