
services:
  promotions:
    build: .
    container_name: promotions-service
    restart: always
    ports:
      - "3007:3007"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    #external: true