
services:
  promotions:
    build: .
    container_name: groups-service
    restart: always
    ports:
      - "3004:3004"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external: true