
services:
  promotions:
    build: .
    container_name: report-service
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
    external: true