
services:
  promotions:
    build: .
    container_name: service-users
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:
