
services:
  notations:
    build: .
    container_name: service-notation
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - .env
    networks:
      - backend
      
networks:
  backend:


